### ISSUE TITLE
Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.

### ISSUE THREAD

**Issue by q2apro** [lrsjng/jquery-qrcode#50]
It is a bit weird, the qrcode rending suddenly stopped working (latest Chrome 74.0.3729.169), throwing this error:

```
    jquery-qrcode-0.17.0.js:220 Uncaught DOMException: Failed to execute 'drawImage' on 'CanvasRenderingContext2D': The HTMLImageElement provided is in the 'broken' state.
    at draw_background_img (jquery-qrcode-0.17.0.js:220:11)
    at draw_background (jquery-qrcode-0.17.0.js:236:5)
    at draw_on_canvas (jquery-qrcode-0.17.0.js:387:3)
    at create_canvas (jquery-qrcode-0.17.0.js:395:10)
    at create_img (jquery-qrcode-0.17.0.js:400:35)
    at create_html (jquery-qrcode-0.17.0.js:461:12)
    at HTMLDivElement.<anonymous> (jquery-qrcode-0.17.0.js:512:21)
    at Function.each (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:2715)
    at r.fn.init.each (https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js:2:1003)
    at r.fn.init.main [as qrcode] (jquery-qrcode-0.17.0.js:508:15)
```

Line:

    context.drawImage(settings.image, sl * size, st * size, sw * size, sh * size);

Maybe `var context = $canvas[0].getContext('2d');` is not set correctly?

**Comment by q2apro** [comment]
Ah, found the problem:

I was using the image with empty `src` attribute:

    <img id="lightbox-img" alt="Lightbox" src="data:," />

That was the culprit.

Now I have `src=""` and it works.
